music.setVolume(255)
basic.forever(function () {
    music.playTone(131, music.beat(BeatFraction.Half))
    music.playTone(175, music.beat(BeatFraction.Half))
    music.playTone(247, music.beat(BeatFraction.Whole))
    music.playTone(330, music.beat(BeatFraction.Quarter))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(185, music.beat(BeatFraction.Quarter))
    music.playTone(185, music.beat(BeatFraction.Quarter))
    music.playTone(185, music.beat(BeatFraction.Quarter))
})
